<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Employee NameInvalidJob Title-- Select_c0cada</name>
   <tag></tag>
   <elementGuidId>6980faa0-0711-4f41-8a78-85f3f9479eda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[2]/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.oxd-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>b1e940bb-12dc-4caa-8495-e796a1e99465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-form</value>
      <webElementGuid>f7900938-761c-4f8c-9642-3f1bea393392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee NameInvalidJob Title-- Select --Sub Unit-- Select --IncludeCurrent Employees OnlyReview Status-- Select --From DateTo Date Reset  Search </value>
      <webElementGuid>8724c246-2f53-494c-92a4-7f94e659f884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;oxd-table-filter&quot;]/div[@class=&quot;oxd-table-filter-area&quot;]/form[@class=&quot;oxd-form&quot;]</value>
      <webElementGuid>b8165eda-c179-4532-8597-46e2ec72e71e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[2]/form</value>
      <webElementGuid>eeca6a62-764c-40aa-ad32-52f7494225d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>a9b4b0a8-8e2b-4e68-a590-083579ea9324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Employee NameInvalidJob Title-- Select --Sub Unit-- Select --IncludeCurrent Employees OnlyReview Status-- Select --From DateTo Date Reset  Search ' or . = 'Employee NameInvalidJob Title-- Select --Sub Unit-- Select --IncludeCurrent Employees OnlyReview Status-- Select --From DateTo Date Reset  Search ')]</value>
      <webElementGuid>99dd244c-6cb2-4f82-b18e-71039e00c515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
